### ISSUE TITLE
Why Dont you publish your library to Maven Central

### ISSUE THREAD

**Issue by CodeCraftPlugin** [Appu26J/JWinRegistry#1]
Greeting As a Java Developer myself
This Project seems quite promising with its use case
So why don't you publish it to maven central

**Comment by Appu26J** [comment]
I don't really know about how to publish stuff to maven central lol

**Comment by CodeCraftPlugin** [comment]
ohh thats not a big issue though it is a bit challanging at first its fairly easy once things are setup

[OSSRH Publish guide](https://central.sonatype.org/publish/publish-guide/
)
this might help 
ohh and considering you are beginner you should use maven but that upto you
